export const POST_BLOG_REQUEST = "POST_BLOG_REQUEST";
export const POST_BLOG_SUCCESS = "POST_BLOG_SUCCESS";
export const POST_BLOG_SUCCESS_RESET = "POST_BLOG_SUCCESS_RESET";
export const POST_BLOG_FAIL = "POST_BLOG_FAIL";

export const GET_SINGLE_BLOG_REQUEST = "GET_SINGLE_BLOG_REQUEST";
export const GET_SINGLE_BLOG_SUCCESS = "GET_SINGLE_BLOG_SUCCESS";
export const GET_SINGLE_BLOG_FAIL = "GET_SINGLE_BLOG_FAIL";

export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";
export const UPDATE_BLOG_RESET = "UPDATE_BLOG_RESET";

export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_FAIL = "GET_BLOGS_FAIL";

export const GET_USER_BLOGS_REQUEST = "GET_USER_BLOGS_REQUEST";
export const GET_USER_BLOGS_SUCCESS = "GET_USER_BLOGS_SUCCESS";
export const GET_USER_BLOGS_FAIL = "GET_USER_BLOGS_FAIL";

export const DELETE_PERSONAL_BLOG_REQUEST = "DELETE_PERSONAL_BLOG_REQUEST";
export const DELETE_PERSONAL_BLOG_SUCCESS = "DELETE_PERSONAL_BLOG_SUCCESS";
export const DELETE_PERSONAL_BLOG_SUCCESS_RESET =
  "DELETE_PERSONAL_BLOG_SUCCESS_RESET";
export const DELETE_PERSONAL_BLOG_FAIL = "DELETE_PERSONAL_BLOG_FAIL";
